"""More lines to type, in the sixteen newer languages.

`snippets2` gave each of them twelve, which is one sitting for anyone who
does a dozen goes at a thing. This is the rest: another twenty or so
each, chosen the same way — the punctuation your hands will actually
meet in that language, rather than one idea translated sixteen times.

The same division of honesty as before, and it has moved. Nine of these
languages now have a toolchain here, and their *blocks* — whole programs
— are in `blocks_new` and are run by the suite. The lines below are
fragments, which is what makes them typing practice, and a fragment
cannot be executed in any language. For the seven without a toolchain —
Kotlin, Swift, Scala, Haskell, OCaml, Elixir and Assembly — the lines are
written from documentation and read carefully, which is weaker, and
saying so is better than implying a check that was not run.
"""

from __future__ import annotations

from code_coach.typing.snippets import Passage, _s

GO_MORE: tuple[Passage, ...] = (
    _s("type Reader interface {", "an interface, which is just a set of methods"),
    _s("func (p Point) Sum() int {", "a method, and its receiver"),
    _s("var _ Stringer = (*Point)(nil)", "the compile-time interface check"),
    _s("if v, ok := m[key]; ok {", "lookup and test in one statement"),
    _s("switch x := v.(type) {", "the type switch"),
    _s("sort.Slice(xs, func(i, j int) bool { return xs[i] < xs[j] })",
       "a comparison written inline"),
    _s("wg.Add(1)", "before the goroutine, never inside it"),
    _s("defer wg.Done()", "and the first line of the goroutine"),
    _s("mu.Lock()", "the mutex, taken"),
    _s("select {", "waiting on more than one channel"),
    _s("case <-ctx.Done():", "the cancellation arm"),
    _s("return fmt.Errorf(\"reading %s: %w\", name, err)", "wrapping, with %w"),
    _s("if errors.Is(err, os.ErrNotExist) {", "unwrapping, with Is"),
    _s("b := strings.Builder{}", "the way to join strings without copying"),
    _s("copy(dst, src)", "returns how many it copied"),
    _s("xs = append(xs[:i], xs[i+1:]...)", "deleting from a slice"),
    _s("t.Helper()", "so failures point at the caller"),
    _s("if got != want {", "the first line of every Go test failure"),
    _s("t.Errorf(\"got %v, want %v\", got, want)", "and the second"),
    _s("//go:embed schema.sql", "a file, compiled in"),
)

PHP_MORE: tuple[Passage, ...] = (
    _s("public function jsonSerialize(): array", "what the interface asks for"),
    _s("final class Order implements JsonSerializable", "a class, closed"),
    _s("public function __construct(private readonly int $id) {}",
       "constructor promotion, and readonly"),
    _s("public static function fromArray(array $row): self",
       "a named constructor"),
    _s("return match (true) {", "match, which is switch that returns"),
    _s("$total = array_sum(array_column($rows, 'price'));",
       "two array functions, nested"),
    _s("usort($rows, fn($a, $b) => $a['id'] <=> $b['id']);",
       "the spaceship, and the arrow function"),
    _s("$names = array_map(static fn(User $u): string => $u->name, $users);",
       "a typed arrow function"),
    _s("[$first, $second] = $pair;", "list assignment, the short way"),
    _s("$config['db']['host'] ??= 'localhost';", "null-coalescing assignment"),
    _s("$order?->customer?->name", "the nullsafe chain"),
    _s("foreach ($rows as ['id' => $id, 'name' => $name]) {",
       "destructuring in the loop header"),
    _s("yield $line;", "which turns the function into a generator"),
    _s("throw new InvalidArgumentException(sprintf('bad id: %d', $id));",
       "sprintf, and a specific exception"),
    _s("} finally {", "the block that runs either way"),
    _s("#[Attribute]", "an attribute, which used to be a comment"),
    _s("use App\\Models\\Order;", "the import, with backslashes"),
    _s("namespace App\\Services;", "and where this file lives"),
    _s("$this->assertSame(3, $result);", "same, not equals"),
    _s("var_dump($value);", "the debugging line everybody types"),
)

LUA_MORE: tuple[Passage, ...] = (
    _s("local ok, err = xpcall(risky, debug.traceback)", "pcall, with a trace"),
    _s("if not ok then", "and the check that follows it"),
    _s("local t = setmetatable({}, {__index = base})", "inheritance, by hand"),
    _s("function M.new(opts)", "the module table pattern"),
    _s("return setmetatable(self, M)", "and what it returns"),
    _s("for k, v in pairs(config) do", "pairs, for a table with names"),
    _s("table.insert(items, 1, value)", "insert at a position"),
    _s("table.remove(items)", "and remove from the end"),
    _s("table.concat(parts, ', ')", "join, which is how you build strings"),
    _s("local n = select('#', ...)", "counting the varargs"),
    _s("local args = {...}", "and collecting them"),
    _s("string.format('%s scored %d', name, score)", "format, not concat"),
    _s("s:gsub('%s+', ' ')", "a pattern, which is not a regex"),
    _s("s:find('lua', 1, true)", "the true means plain text"),
    _s("os.time()", "seconds, as a number"),
    _s("io.write(line, '\\n')", "write, when print adds too much"),
    _s("coroutine.yield(value)", "the other way Lua does concurrency"),
    _s("goto continue", "the one Lua does have"),
    _s("::continue::", "and the label it jumps to"),
    _s("local unpack = table.unpack or unpack", "the version dance"),
)

RUBY_MORE: tuple[Passage, ...] = (
    _s("module Greetable", "a mixin starts here"),
    _s("extend self", "so the module's methods are its own"),
    _s("attr_accessor :name, :email", "reader and writer, both"),
    _s("def initialize(name:, email: nil)", "keyword arguments, one required"),
    _s("@items ||= []", "memoise, in one line"),
    _s("items.each_with_object({}) { |i, h| h[i.id] = i }",
       "each_with_object, which keeps the hash"),
    _s("items.group_by(&:status)", "the symbol-to-proc ampersand"),
    _s("items.sum(&:price)", "sum, with a block"),
    _s("items.sort_by { |i| [-i.score, i.name] }",
       "sorting by two things at once"),
    _s("items.partition { |i| i.active? }", "two arrays out, one pass"),
    _s("raise ArgumentError, \"unknown status: #{status}\"",
       "raise with interpolation"),
    _s("rescue => e", "the bare rescue, which catches StandardError"),
    _s("ensure", "and the block that always runs"),
    _s("def each(&block)", "taking a block as a value"),
    _s("yield(item) if block_given?", "or not taking it at all"),
    _s("case status", "case, which uses ==="),
    _s("in {name: String => name}", "pattern matching, Ruby 3"),
    _s("Data.define(:x, :y)", "the immutable value object"),
    _s("frozen_string_literal: true", "the magic comment"),
    _s("puts items.map(&:to_s).join(\", \")", "map, symbol, join"),
)

JAVA_MORE: tuple[Passage, ...] = (
    _s("record Money(long cents, String currency) {}", "a record, which is the whole class"),
    _s("sealed interface Shape permits Circle, Square {}",
       "sealed, so the switch can be exhaustive"),
    _s("public Optional<User> findById(long id) {", "Optional, not null"),
    _s("return Optional.ofNullable(map.get(id));", "and how you make one"),
    _s("user.map(User::name).orElse(\"unknown\")", "the chain that avoids a null check"),
    _s("var names = new ArrayList<String>();", "var, on the left only"),
    _s("list.stream().collect(Collectors.groupingBy(User::city))",
       "groupingBy, which is the one worth knowing"),
    _s("IntStream.rangeClosed(1, 10).sum()", "a range without a loop"),
    _s("try (var stream = Files.lines(path)) {",
       "try-with-resources, which closes for you"),
    _s("throw new UnsupportedOperationException(\"read only\");",
       "the exception for a method that should not exist"),
    _s("@Override", "the annotation that catches a typo"),
    _s("private static final Logger log = LoggerFactory.getLogger(Main.class);",
       "the most copied line in Java"),
    _s("switch (shape) {", "and since 14 it can return a value"),
    _s("case Circle c -> c.radius() * 2;", "pattern matching in a switch arm"),
    _s("if (obj instanceof User u && u.active()) {",
       "instanceof that binds a name"),
    _s("String text = \"\"\"", "the text block, which opens on its own line"),
    _s("Objects.requireNonNull(name, \"name\");", "fail here, not three frames later"),
    _s("assertThrows(IllegalArgumentException.class, () -> parse(\"x\"));",
       "asserting on a throw"),
    _s("CompletableFuture.supplyAsync(this::load)", "async, without a framework"),
    _s("Thread.ofVirtual().start(task);", "a virtual thread, which is cheap"),
)

CSHARP_MORE: tuple[Passage, ...] = (
    _s("namespace App.Services;", "the file-scoped namespace"),
    _s("public sealed record Point(int X, int Y);", "a record, in one line"),
    _s("public required string Name { get; init; }", "required, and init-only"),
    _s("public int Total => Items.Sum(i => i.Price);", "an expression-bodied property"),
    _s("var result = value switch", "the switch expression"),
    _s("_ => throw new ArgumentOutOfRangeException(nameof(value)),",
       "the discard arm, and nameof"),
    _s("if (obj is User { Active: true } user)", "a property pattern that binds"),
    _s("await using var conn = await OpenAsync(ct);", "async disposal"),
    _s("public async Task<IReadOnlyList<User>> GetAsync(CancellationToken ct)",
       "the signature everything ends up having"),
    _s("await foreach (var row in Query(ct))", "an async stream"),
    _s("cancellationToken.ThrowIfCancellationRequested();", "the cooperative check"),
    _s("ArgumentNullException.ThrowIfNull(name);", "the modern guard clause"),
    _s("string? maybe = null;", "the question mark that turns on the warnings"),
    _s("return name ?? throw new InvalidOperationException();",
       "throw, used as an expression"),
    _s("items.Where(i => i.Active).OrderBy(i => i.Name).ToList()",
       "three LINQ calls, chained"),
    _s("Span<byte> buffer = stackalloc byte[256];", "a span, with no allocation"),
    _s("[JsonPropertyName(\"created_at\")]", "an attribute on a property"),
    _s("services.AddSingleton<IClock, SystemClock>();", "registering a dependency"),
    _s("Assert.Equal(expected, actual);", "expected first, always"),
    _s("#nullable enable", "the pragma, for a file that lags the project"),
)

ODIN_MORE: tuple[Passage, ...] = (
    _s("Error :: enum {None, NotFound, Denied}", "an enum, declared with ::"),
    _s("Result :: union {int, Error}", "a union, which is the error type"),
    _s("value, err := lookup(key)", "two returns, like Go"),
    _s("if err != .None {", "the implicit enum selector"),
    _s("items := make([dynamic]int, 0, 16)", "length and capacity"),
    _s("reserve(&items, 64)", "asking for room before you need it"),
    _s("append(&items, value)", "append takes a pointer here"),
    _s("context.allocator = context.temp_allocator", "swapping the allocator"),
    _s("defer free_all(context.temp_allocator)", "and clearing it in one go"),
    _s("for item, index in items {", "value first, index second"),
    _s("#partial switch value in shape {", "a switch that need not be complete"),
    _s("case Circle: fmt.println(value.radius)", "and the arm that narrows it"),
    _s("Vec3 :: distinct [3]f32", "distinct, so it is not just an array"),
    _s("v := Vec3{1, 2, 3} * 2", "array programming, built in"),
    _s("when ODIN_OS == .Windows {", "compile-time branching"),
    _s("foreign import user32 \"system:User32.lib\"", "calling into C"),
    _s("proc \"c\" (hwnd: rawptr) -> i32", "and the calling convention"),
    _s("assert(len(items) > 0)", "which compiles out in release"),
    _s("testing.expect(t, got == want)", "the test assertion"),
    _s("fmt.printf(\"%v %T\\n\", value, value)", "the value, and its type"),
)

ZIG_MORE: tuple[Passage, ...] = (
    _s("const Allocator = std.mem.Allocator;", "the type everything asks for"),
    _s("var gpa = std.heap.GeneralPurposeAllocator(.{}){};", "the debug allocator"),
    _s("defer _ = gpa.deinit();", "which tells you if you leaked"),
    _s("var list = std.ArrayList(u8).init(allocator);", "a growable list"),
    _s("defer list.deinit();", "and the line that must follow it"),
    _s("try list.appendSlice(\"hello\");", "appending, which can fail"),
    _s("const Shape = union(enum) { circle: f32, square: f32 };",
       "a tagged union"),
    _s("switch (shape) {", "and the switch that must cover it"),
    _s("const value = map.get(key) orelse return error.Missing;",
       "orelse, on an optional"),
    _s("while (it.next()) |entry| {", "unwrapping, once per turn of the loop"),
    _s("errdefer list.deinit();", "cleanup, only on the failure path"),
    _s("comptime var i: usize = 0;", "a loop the compiler runs"),
    _s("inline for (fields) |field| {", "unrolled at compile time"),
    _s("@typeInfo(T).@\"struct\".fields", "reflection, without a runtime"),
    _s("std.debug.assert(len > 0);", "which is a crash in debug and nothing in release"),
    _s("std.debug.print(\"{any}\\n\", .{value});", "printing to stderr"),
    _s("try std.testing.expectEqualStrings(want, got);", "the string assertion"),
    _s("const builtin = @import(\"builtin\");", "what the compiler knows"),
    _s("if (builtin.mode == .Debug) {", "and branching on it"),
    _s("export fn add(a: i32, b: i32) i32 {", "a function C can call"),
)

LISP_MORE: tuple[Passage, ...] = (
    _s("(defpackage :app (:use :cl))", "a package, and what it inherits"),
    _s("(in-package :app)", "and the line every file after it needs"),
    _s("(defstruct point x y)", "a struct, and four functions for free"),
    _s("(defclass account () ((balance :initform 0)))", "CLOS, briefly"),
    _s("(defgeneric describe-it (thing))", "the generic function"),
    _s("(defmethod describe-it ((thing point))", "and a method on a type"),
    _s("(defmacro unless-zero (n &body body)", "a macro takes the code itself"),
    _s("`(if (zerop ,n) nil (progn ,@body))", "backquote, comma, comma-at"),
    _s("(let* ((a 1) (b (+ a 1)))", "let-star, when the second needs the first"),
    _s("(multiple-value-bind (value found) (gethash k table)", "two values, named"),
    _s("(handler-case (risky) (error (e) (format t \"~a~%\" e)))",
       "catching a condition"),
    _s("(loop for x across vec collect (* x x))", "across, for a vector"),
    _s("(loop for (k . v) in pairs do", "destructuring a cons in the loop"),
    _s("(mapcar (lambda (x) (* x 2)) xs)", "map, and the lambda"),
    _s("(remove-if-not #'evenp xs)", "the sharp-quote, naming a function"),
    _s("(setf (gethash key table) value)", "setf on a place, not a variable"),
    _s("(push item stack)", "and pop, which is its opposite"),
    _s("(format t \"~{~a~^, ~}~%\" items)", "the format directive that joins"),
    _s("(declaim (optimize (speed 3) (safety 1)))", "telling the compiler what you want"),
    _s("(assert (> n 0) (n) \"n must be positive\")", "assert, which offers to fix it"),
)

KOTLIN_MORE: tuple[Passage, ...] = (
    _s("data class Money(val cents: Long, val currency: String)",
       "equals, hashCode and copy, free"),
    _s("sealed interface Result<out T>", "a closed hierarchy"),
    _s("val total = items.sumOf { it.price }", "it, the implicit parameter"),
    _s("items.filter { it.active }.map { it.name }", "two lambdas, chained"),
    _s("fun User.displayName(): String = \"$name <$email>\"",
       "an extension function"),
    _s("val name: String by lazy { compute() }", "delegated, computed once"),
    _s("value?.let { use(it) }", "the null-safe scope function"),
    _s("requireNotNull(value) { \"value was null\" }", "the guard, with a message"),
    _s("when (shape) {", "when, which is exhaustive on a sealed type"),
    _s("is Circle -> shape.radius * 2", "the arm that smart-casts"),
    _s("suspend fun load(): List<User>", "the keyword that makes it async"),
    _s("coroutineScope {", "and the scope that waits for its children"),
    _s("launch { work() }", "fire and forget, inside the scope"),
    _s("val deferred = async { fetch() }", "and the one that returns"),
    _s("flow { emit(value) }", "a cold stream"),
    _s("withContext(Dispatchers.IO) {", "moving work off the main thread"),
    _s("companion object {", "where the static things live"),
    _s("init {", "and the block that runs on construction"),
    _s("@Serializable", "the annotation kotlinx reads"),
    _s("assertEquals(expected, actual)", "expected first"),
)

SWIFT_MORE: tuple[Passage, ...] = (
    _s("struct Point: Equatable, Hashable {", "two protocols, both synthesised"),
    _s("enum Result<Success, Failure: Error>", "the generic with a constraint"),
    _s("guard let value = maybe else { return }", "the early exit"),
    _s("if case .success(let value) = result {", "matching one case"),
    _s("let names = users.map(\\.name)", "the key path shorthand"),
    _s("items.filter { $0.active }", "the positional parameter"),
    _s("func load() async throws -> [User]", "async and throws, together"),
    _s("let users = try await client.fetch()", "and how you call it"),
    _s("Task { await refresh() }", "starting async work from sync code"),
    _s("actor Cache {", "an actor, which owns its state"),
    _s("@MainActor func update()", "and the one that means the UI thread"),
    _s("withTaskGroup(of: Int.self) { group in", "structured concurrency"),
    _s("defer { file.close() }", "runs when the scope ends"),
    _s("extension User: CustomStringConvertible {", "conformance, added later"),
    _s("var body: some View {", "the line every SwiftUI view has"),
    _s("@State private var count = 0", "and the property wrapper"),
    _s("some Collection where Element == Int", "an opaque type, constrained"),
    _s("precondition(index >= 0, \"negative index\")", "which holds in release too"),
    _s("#expect(result == 42)", "Swift Testing, not XCTest"),
    _s("print(value, terminator: \"\")", "print, without the newline"),
)

SCALA_MORE: tuple[Passage, ...] = (
    _s("enum Shape:", "Scala 3's enum, which is an ADT"),
    _s("case Circle(radius: Double)", "and one of its cases"),
    _s("given Ordering[Point] with", "a given, which replaced implicit"),
    _s("def total(using ctx: Context): Int", "and how you ask for one"),
    _s("extension (s: String) def shout: String = s.toUpperCase",
       "an extension method"),
    _s("val total = items.map(_.price).sum", "the underscore parameter"),
    _s("items.groupBy(_.city).view.mapValues(_.size).toMap",
       "group, map the values, and force it"),
    _s("items.foldLeft(0)((acc, i) => acc + i.price)", "fold, with two lists"),
    _s("for", "the comprehension, on its own line"),
    _s("  case (k, v) <- pairs", "and the generator that destructures"),
    _s("yield k -> v", "which makes it a map"),
    _s("shape match", "match, without parentheses"),
    _s("case Circle(r) => r * 2", "and the case that extracts"),
    _s("opaque type UserId = Long", "a type with no runtime cost"),
    _s("inline def assertPositive(n: Int): Unit =", "inlined at the call site"),
    _s("Try(risky()).toEither", "turning a throw into a value"),
    _s("Future.sequence(futures)", "many futures into one"),
    _s("case class Config(host: String = \"localhost\")", "a default argument"),
    _s("@main def run(args: String*): Unit =", "varargs, with a star"),
    _s("assert(result == expected)", "the plain one"),
)

HASKELL_MORE: tuple[Passage, ...] = (
    _s("{-# LANGUAGE OverloadedStrings #-}", "the pragma at the top"),
    _s("module Main (main) where", "and what the module exports"),
    _s("data Shape = Circle Double | Square Double", "a sum type"),
    _s("newtype UserId = UserId Int deriving (Eq, Show)", "a wrapper with no cost"),
    _s("class Describable a where", "a type class"),
    _s("instance Describable Shape where", "and an instance of it"),
    _s("area :: Shape -> Double", "the signature, always first"),
    _s("area (Circle r) = pi * r * r", "and the equation that matches"),
    _s("total = foldr (+) 0", "point-free, with a fold"),
    _s("map (*2) . filter even $ xs", "composition, then application"),
    _s("xs >>= \\x -> [x, x]", "bind, on a list"),
    _s("pure <$> Just 3 <*> Just 4", "applicative style"),
    _s("maybe 0 (*2) value", "the eliminator, without a case"),
    _s("  Nothing -> 0", "the empty one"),
    _s("  Just v  -> v * 2", "and the one with a value"),
    _s("where go acc [] = acc", "a local helper, after the fact"),
    _s("main = do", "do notation, which is not imperative"),
    _s("  line <- getLine", "the arrow that pulls a value out"),
    _s("  putStrLn $ \"hello \" ++ line", "the dollar that avoids parentheses"),
    _s("print (length xs)", "print, which needs Show"),
)

OCAML_MORE: tuple[Passage, ...] = (
    _s("type shape = Circle of float | Square of float", "a variant type"),
    _s("let area = function", "a function defined by its cases"),
    _s("  | Circle r -> Float.pi *. r *. r", "the float operators have dots"),
    _s("type user = { name : string; age : int }", "a record"),
    _s("let p = { x = 3; y = 4 }", "and one of them"),
    _s("let { x; _ } = p in", "destructuring, ignoring the rest"),
    _s("let rec loop acc = function", "rec, and an accumulator"),
    _s("List.fold_left ( + ) 0 xs", "an operator, passed as a value"),
    _s("List.map (fun x -> x * 2) xs", "the lambda keyword is fun"),
    _s("xs |> List.filter even |> List.length", "the pipe, left to right"),
    _s("match maybe with", "match, and its arms"),
    _s("| None -> 0", "the empty case"),
    _s("| Some v -> v * 2", "and the one with something in it"),
    _s("module Cache : sig", "a module, and its signature"),
    _s("  val get : string -> int option", "which is the interface"),
    _s("let () = Printf.printf \"%d\\n\" total", "printf, checked at compile time"),
    _s("try risky () with Not_found -> 0", "exceptions, which OCaml does have"),
    _s("Hashtbl.replace table key value", "replace, not add, unless you mean it"),
    _s("let open List in", "a local open"),
    _s("assert (n > 0)", "the assertion"),
)

ELIXIR_MORE: tuple[Passage, ...] = (
    _s("defstruct [:name, :email]", "a struct, from a keyword list"),
    _s("@enforce_keys [:name]", "and the one it will not do without"),
    _s("def total(items) when is_list(items) do", "a guard on the head"),
    _s("items |> Enum.map(& &1.price) |> Enum.sum()", "the capture, twice"),
    _s("Enum.reduce(items, 0, fn i, acc -> acc + i end)", "reduce, written out"),
    _s("with {:ok, user} <- fetch(id),", "with, for a chain that can fail"),
    _s("else", "and where it goes when one does"),
    _s("case result do", "case, on a tagged tuple"),
    _s("  {:ok, value} -> value", "the happy arm"),
    _s("  {:error, reason} -> raise reason", "and the other"),
    _s("{:noreply, state}", "what a GenServer handle_cast returns"),
    _s("def handle_call(:get, _from, state) do", "and a call, which replies"),
    _s("GenServer.start_link(__MODULE__, :ok, name: __MODULE__)",
       "starting one, named after itself"),
    _s("Supervisor.init(children, strategy: :one_for_one)", "the restart strategy"),
    _s("Task.async_stream(items, &work/1, max_concurrency: 8)",
       "concurrency with a limit"),
    _s("receive do", "the mailbox, directly"),
    _s("after 5_000 ->", "and the timeout arm"),
    _s("@spec total(list(Item.t())) :: integer()", "the typespec dialyzer reads"),
    _s("IO.inspect(value, label: \"here\")", "the debugging line, labelled"),
    _s("assert {:ok, _} = run()", "assert on a match, not a boolean"),
)

ASSEMBLY_MORE: tuple[Passage, ...] = (
    _s("section .bss", "where the uninitialised bytes go"),
    _s("buffer resb 64", "reserve sixty-four of them"),
    _s("extern printf", "a symbol from somewhere else"),
    _s("_start:", "and the label it lands on"),
    _s("pop rbp", "the epilogue, last line but one"),
    _s("mov rbp, rsp", "and its second"),
    _s("sub rsp, 32", "room for locals"),
    _s("lea rax, [rel msg]", "an address, not the bytes at it"),
    _s("xor eax, eax", "the fast way to write zero"),
    _s("test rax, rax", "and the fast way to compare with it"),
    _s("jz .done", "jump if the zero flag is set"),
    _s("cmp rdi, rsi", "compare two registers"),
    _s("jge .loop", "jump if greater or equal"),
    _s("inc rcx", "one more"),
    _s("imul rax, rbx", "signed multiply"),
    _s("call printf wrt ..plt", "calling into libc"),
    _s("mov rax, 60", "the exit syscall number"),
    _s("int 0x80", "the older way to ask the kernel"),
    _s("ret", "which pops the return address"),
    _s("align 16", "because the ABI asks for it"),
)


BY_LANGUAGE: dict[str, tuple[Passage, ...]] = {
    "go": GO_MORE,
    "php": PHP_MORE,
    "lua": LUA_MORE,
    "ruby": RUBY_MORE,
    "java": JAVA_MORE,
    "csharp": CSHARP_MORE,
    "odin": ODIN_MORE,
    "zig": ZIG_MORE,
    "lisp": LISP_MORE,
    "kotlin": KOTLIN_MORE,
    "swift": SWIFT_MORE,
    "scala": SCALA_MORE,
    "haskell": HASKELL_MORE,
    "ocaml": OCAML_MORE,
    "elixir": ELIXIR_MORE,
    "assembly": ASSEMBLY_MORE,
}
