"""A thesaurus you can walk through.

Not a word list: a graph. Each entry knows a few words near it in meaning, so
a drill can start somewhere and wander — candid to frank to blunt to abrupt —
showing each word's definition on the way. That's the rabbit hole you fall
into with a paper thesaurus open on the desk, which is a better twenty minutes
than typing the same sentence again.

Every `near` name must be an entry in this file, so a walk can never reach a
dead end. There's a test for it.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Entry:
    word: str
    meaning: str
    # A few words close to this one. The walk steps along these.
    near: tuple[str, ...]


def _e(word: str, meaning: str, *near: str) -> Entry:
    return Entry(word, meaning, near)


ENTRIES: tuple[Entry, ...] = (
    # ── Saying what you mean ────────────────────────────────
    _e("candid", "honest, even when it's awkward", "frank", "blunt", "sincere"),
    _e("frank", "open and direct, without softening it", "candid", "blunt", "plain"),
    _e("blunt", "direct to the point of rudeness", "frank", "abrupt", "curt"),
    _e("curt", "so brief it seems unfriendly", "blunt", "abrupt", "terse"),
    _e("terse", "short and to the point, and slightly cold with it", "curt", "concise", "succinct"),
    _e("concise", "short and complete at once", "terse", "succinct", "brief"),
    _e("succinct", "said in few words, and none wasted", "concise", "brief", "pithy"),
    _e("pithy", "brief and full of meaning at the same time", "succinct", "concise", "apt"),
    _e("brief", "not lasting or taking long", "concise", "succinct", "fleeting"),
    _e("plain", "simple and unadorned", "frank", "clear", "stark"),
    _e("sincere", "meaning what you say", "candid", "genuine", "earnest"),
    _e("genuine", "real rather than imitation", "sincere", "authentic", "earnest"),
    _e("authentic", "actually what it claims to be", "genuine", "true", "original"),
    _e("earnest", "serious and meaning it", "sincere", "genuine", "grave"),
    _e("abrupt", "sudden, without warning", "blunt", "curt", "sudden"),

    # ── Clear and unclear ───────────────────────────────────
    _e("clear", "easy to see or understand", "plain", "lucid", "obvious"),
    _e("lucid", "clearly expressed, and easy to follow", "clear", "coherent", "articulate"),
    _e("coherent", "hangs together and makes sense", "lucid", "logical", "consistent"),
    _e("articulate", "able to say things well", "lucid", "eloquent", "fluent"),
    _e("eloquent", "persuasive and pleasant to listen to", "articulate", "fluent", "expressive"),
    _e("fluent", "flowing easily, without hesitation", "articulate", "eloquent", "smooth"),
    _e("obscure", "hard to see or understand", "vague", "cryptic", "opaque"),
    _e("vague", "not stated precisely enough to act on", "obscure", "ambiguous", "hazy"),
    _e("ambiguous", "open to more than one reading", "vague", "equivocal", "obscure"),
    _e("cryptic", "deliberately hard to interpret", "obscure", "enigmatic", "opaque"),
    _e("enigmatic", "mysterious, and seemingly on purpose", "cryptic", "puzzling", "obscure"),
    _e("opaque", "letting nothing through, literally or otherwise", "cryptic", "obscure", "dense"),
    _e("equivocal", "worded so it can be taken either way", "ambiguous", "evasive", "vague"),

    # ── Careful and careless ────────────────────────────────
    _e("meticulous", "careful about every small detail", "thorough", "precise", "diligent"),
    _e("thorough", "leaving nothing out", "meticulous", "exhaustive", "rigorous"),
    _e("rigorous", "thorough and exacting", "thorough", "strict", "precise"),
    _e("precise", "exact, with no room for doubt", "meticulous", "accurate", "rigorous"),
    _e("accurate", "matching the truth or the target", "precise", "correct", "exact"),
    _e("exact", "right down to the last detail", "accurate", "precise", "literal"),
    _e("diligent", "steady and careful in effort", "meticulous", "assiduous", "industrious"),
    _e("assiduous", "working at something constantly and carefully", "diligent", "persistent", "industrious"),
    _e("careless", "not taking enough care", "sloppy", "negligent", "hasty"),
    _e("sloppy", "done without care or neatness", "careless", "slapdash", "hasty"),
    _e("negligent", "failing to do what care required", "careless", "remiss", "lax"),
    _e("hasty", "done too quickly to be done well", "careless", "rash", "abrupt"),
    _e("rash", "acting before thinking", "hasty", "reckless", "impulsive"),
    _e("reckless", "not caring about the risk", "rash", "impulsive", "bold"),
    _e("impulsive", "acting on the moment's feeling", "rash", "reckless", "spontaneous"),

    # ── Steady and strong ───────────────────────────────────
    _e("resilient", "recovers quickly from difficulty", "robust", "hardy", "tenacious"),
    _e("robust", "keeps working under strain", "resilient", "sturdy", "durable"),
    _e("sturdy", "solidly built and hard to upset", "robust", "durable", "stable"),
    _e("durable", "lasting a long time without wearing out", "sturdy", "robust", "enduring"),
    _e("enduring", "continuing over a long period", "durable", "persistent", "lasting"),
    _e("persistent", "carrying on despite difficulty", "enduring", "tenacious", "assiduous"),
    _e("tenacious", "holding on and not letting go", "persistent", "resilient", "stubborn"),
    _e("stubborn", "refusing to change, helpfully or otherwise", "tenacious", "obstinate", "rigid"),
    _e("obstinate", "stubborn past the point of reason", "stubborn", "rigid", "intransigent"),
    _e("intransigent", "completely unwilling to compromise", "obstinate", "rigid", "adamant"),
    _e("adamant", "utterly firm about something", "intransigent", "resolute", "obstinate"),
    _e("resolute", "determined and not easily shaken", "adamant", "steadfast", "decisive"),
    _e("steadfast", "loyal and unwavering over time", "resolute", "constant", "enduring"),

    # ── Clever ──────────────────────────────────────────────
    _e("astute", "quick to see what's really going on", "shrewd", "perceptive", "canny"),
    _e("shrewd", "sharp about people and situations", "astute", "canny", "cunning"),
    _e("canny", "careful and quietly clever, especially about money", "shrewd", "astute", "prudent"),
    _e("perceptive", "noticing what others miss", "astute", "observant", "insightful"),
    _e("observant", "paying close attention to what's there", "perceptive", "attentive", "vigilant"),
    _e("insightful", "seeing into how something really works", "perceptive", "profound", "astute"),
    _e("cunning", "clever in a way you might not trust", "shrewd", "crafty", "wily"),
    _e("crafty", "clever at getting round things", "cunning", "wily", "devious"),
    _e("wily", "full of tricks and hard to pin down", "crafty", "cunning", "devious"),
    _e("devious", "taking a dishonest route to something", "wily", "crafty", "evasive"),
    _e("evasive", "avoiding a direct answer", "devious", "equivocal", "elusive"),
    _e("elusive", "hard to catch, find or describe", "evasive", "fleeting", "subtle"),
    _e("prudent", "careful about the consequences", "canny", "cautious", "judicious"),
    _e("cautious", "unwilling to take a risk", "prudent", "wary", "vigilant"),
    _e("wary", "watchful because something might go wrong", "cautious", "vigilant", "guarded"),
    _e("vigilant", "keeping careful watch", "wary", "observant", "attentive"),
    _e("judicious", "showing good judgement", "prudent", "sensible", "wise"),

    # ── Small differences ───────────────────────────────────
    _e("subtle", "so slight it takes noticing", "nuanced", "delicate", "elusive"),
    _e("nuanced", "aware of the small differences that matter", "subtle", "sophisticated", "delicate"),
    _e("delicate", "easily damaged, or finely made", "subtle", "fragile", "fine"),
    _e("fragile", "breaking easily", "delicate", "brittle", "frail"),
    _e("brittle", "hard, and snapping rather than bending", "fragile", "rigid", "stiff"),
    _e("rigid", "not bending at all", "brittle", "stiff", "obstinate"),
    _e("stiff", "resisting being moved or bent", "rigid", "brittle", "taut"),

    # ── Plenty and little ───────────────────────────────────
    _e("abundant", "there is plenty of it", "ample", "plentiful", "copious"),
    _e("ample", "enough and then some", "abundant", "generous", "plentiful"),
    _e("plentiful", "available in large amounts", "abundant", "ample", "copious"),
    _e("copious", "produced in great quantity", "plentiful", "abundant", "profuse"),
    _e("profuse", "poured out freely, sometimes too freely", "copious", "lavish", "excessive"),
    _e("lavish", "spent or given generously", "profuse", "extravagant", "generous"),
    _e("extravagant", "spending more than is sensible", "lavish", "excessive", "profuse"),
    _e("excessive", "more than is needed or reasonable", "extravagant", "redundant", "profuse"),
    _e("redundant", "more than is needed", "excessive", "superfluous", "spare"),
    _e("superfluous", "serving no purpose because it is already covered", "redundant", "excessive", "spare"),
    _e("scarce", "hard to find because there is little of it", "sparse", "meagre", "rare"),
    _e("sparse", "thinly spread", "scarce", "meagre", "spare"),
    _e("meagre", "less than is needed", "sparse", "scarce", "scant"),
    _e("scant", "barely enough", "meagre", "sparse", "slight"),

    # ── Filler that keeps the graph connected ───────────────
    _e("logical", "following sensibly from what came before", "coherent", "consistent", "sensible"),
    _e("consistent", "the same throughout, without contradicting itself", "coherent", "logical", "constant"),
    _e("constant", "not changing over time", "consistent", "steadfast", "stable"),
    _e("stable", "not liable to fall over or change suddenly", "constant", "sturdy", "steady"),
    _e("steady", "even and unhurried", "stable", "constant", "smooth"),
    _e("smooth", "without bumps or interruptions", "steady", "fluent", "even"),
    _e("even", "level, equal, or without variation", "smooth", "steady", "uniform"),
    _e("uniform", "the same everywhere", "even", "consistent", "regular"),
    _e("regular", "happening at predictable intervals", "uniform", "consistent", "routine"),
    _e("routine", "done the same way every time", "regular", "habitual", "ordinary"),
    _e("habitual", "done so often it is automatic", "routine", "regular", "customary"),
    _e("customary", "usual, by long practice", "habitual", "routine", "conventional"),
    _e("conventional", "following the usual way of doing things", "customary", "ordinary", "orthodox"),
    _e("orthodox", "accepted as the standard view", "conventional", "customary", "traditional"),
    _e("traditional", "handed down from earlier generations", "orthodox", "conventional", "customary"),
    _e("ordinary", "nothing unusual about it", "conventional", "routine", "plain"),
    _e("sensible", "showing practical good sense", "judicious", "logical", "pragmatic"),
    _e("pragmatic", "concerned with what actually works", "sensible", "practical", "judicious"),
    _e("practical", "useful in reality rather than in theory", "pragmatic", "sensible", "useful"),
    _e("useful", "able to do something you needed done", "practical", "helpful", "valuable"),
    _e("helpful", "making something easier for somebody", "useful", "supportive", "kind"),
    _e("kind", "caring about how others are doing", "helpful", "generous", "considerate"),
    _e("considerate", "thinking about the effect on other people", "kind", "thoughtful", "attentive"),
    _e("thoughtful", "having thought about it properly", "considerate", "attentive", "reflective"),
    _e("attentive", "paying close and continued attention", "thoughtful", "observant", "vigilant"),
    _e("reflective", "given to thinking things over", "thoughtful", "contemplative", "profound"),
    _e("contemplative", "spending time in quiet thought", "reflective", "profound", "serene"),
    _e("profound", "going far below the surface", "contemplative", "insightful", "deep"),
    _e("deep", "extending a long way down, or into a subject", "profound", "dense", "serious"),
    _e("dense", "packed tightly together", "deep", "opaque", "compact"),
    _e("compact", "taking up little room for what it holds", "dense", "concise", "neat"),
    _e("neat", "tidy and well arranged", "compact", "orderly", "elegant"),
    _e("orderly", "arranged in a sensible order", "neat", "systematic", "methodical"),
    _e("systematic", "done according to a plan, step by step", "orderly", "methodical", "thorough"),
    _e("methodical", "following a set method carefully", "systematic", "orderly", "diligent"),
    _e("elegant", "solving the problem with nothing spare", "neat", "graceful", "refined"),
    _e("graceful", "moving or shaped pleasingly", "elegant", "refined", "smooth"),
    _e("refined", "improved by removing what was coarse", "graceful", "elegant", "polished"),
    _e("polished", "finished to a high standard", "refined", "smooth", "accomplished"),
    _e("accomplished", "skilled through practice", "polished", "adept", "capable"),
    _e("adept", "highly skilled at something", "accomplished", "capable", "proficient"),
    _e("capable", "able to do what is required", "adept", "competent", "proficient"),
    _e("competent", "good enough at the job", "capable", "proficient", "adequate"),
    _e("proficient", "well practised and reliably good", "competent", "adept", "capable"),
    _e("adequate", "enough, but no more than that", "competent", "sufficient", "passable"),
    _e("sufficient", "as much as is needed", "adequate", "ample", "enough"),
    _e("enough", "the amount that will do", "sufficient", "adequate", "ample"),
    _e("passable", "acceptable without being good", "adequate", "tolerable", "ordinary"),
    _e("tolerable", "bearable, if not enjoyable", "passable", "adequate", "modest"),
    _e("modest", "not large, and not boastful", "tolerable", "humble", "slight"),
    _e("humble", "not thinking too much of yourself", "modest", "unassuming", "meek"),
    _e("unassuming", "making no claims about yourself", "humble", "modest", "meek"),
    _e("meek", "quiet and unwilling to assert yourself", "humble", "unassuming", "gentle"),
    _e("gentle", "soft in manner or in force", "meek", "kind", "mild"),
    _e("moderate", "avoiding extremes", "mild", "temperate", "reasonable"),
    _e("temperate", "restrained, and neither hot nor cold", "moderate", "mild", "reasonable"),
    _e("reasonable", "fair, and within sensible limits", "moderate", "sensible", "fair"),
    _e("fair", "treating everyone as they deserve", "reasonable", "just", "impartial"),
    _e("just", "morally right and deserved", "fair", "impartial", "equitable"),
    _e("impartial", "not favouring one side", "fair", "just", "objective"),
    _e("equitable", "fair to everyone involved", "just", "impartial", "fair"),
    _e("objective", "based on facts rather than feelings", "impartial", "detached", "factual"),
    _e("detached", "not emotionally involved", "objective", "aloof", "impartial"),
    _e("aloof", "keeping a distance from others", "detached", "reserved", "remote"),
    _e("reserved", "keeping thoughts and feelings private", "aloof", "guarded", "quiet"),
    _e("guarded", "careful about what you reveal", "reserved", "wary", "cautious"),
    _e("quiet", "making little noise, or saying little", "reserved", "serene", "calm"),
    _e("serene", "calm and untroubled", "quiet", "calm", "contemplative"),
    _e("calm", "not agitated", "serene", "quiet", "composed"),
    _e("composed", "in control of yourself under pressure", "calm", "serene", "steady"),
    _e("factual", "sticking to what can be shown", "objective", "literal", "accurate"),
    _e("literal", "meaning exactly what the words say", "factual", "exact", "plain"),
    _e("true", "matching how things actually are", "authentic", "accurate", "correct"),
    _e("correct", "free from error", "true", "accurate", "right"),
    _e("right", "correct, or morally sound", "correct", "just", "true"),
    _e("original", "the first of its kind, or newly thought of", "authentic", "novel", "inventive"),
    _e("novel", "new and unlike what came before", "original", "inventive", "fresh"),
    _e("inventive", "good at thinking of new things", "novel", "original", "creative"),
    _e("creative", "making something that wasn't there", "inventive", "imaginative", "novel"),
    _e("imaginative", "full of ideas beyond the obvious", "creative", "inventive", "fresh"),
    _e("fresh", "new, and not yet stale", "novel", "imaginative", "original"),
    _e("bold", "willing to take a risk or stand out", "reckless", "brave", "daring"),
    _e("brave", "acting despite fear", "bold", "daring", "courageous"),
    _e("daring", "boldly taking chances", "brave", "bold", "adventurous"),
    _e("courageous", "showing courage over time, not just once", "brave", "resolute", "daring"),
    _e("adventurous", "keen to try new and risky things", "daring", "bold", "curious"),
    _e("curious", "wanting to know", "adventurous", "inquisitive", "interested"),
    _e("inquisitive", "asking a lot of questions", "curious", "interested", "probing"),
    _e("interested", "giving something your attention willingly", "curious", "inquisitive", "attentive"),
    _e("probing", "asking questions that go deeper", "inquisitive", "thorough", "searching"),
    _e("searching", "looking hard for something, including in a person", "probing", "thorough", "curious"),
    _e("exhaustive", "covering absolutely everything", "thorough", "comprehensive", "rigorous"),
    _e("comprehensive", "including all of it", "exhaustive", "thorough", "complete"),
    _e("complete", "with nothing missing", "comprehensive", "whole", "finished"),
    _e("whole", "entire, with all parts present", "complete", "intact", "total"),
    _e("intact", "undamaged and still all there", "whole", "complete", "sound"),
    _e("sound", "in good condition, or well reasoned", "intact", "logical", "sturdy"),
    _e("total", "the whole amount, with nothing left out", "whole", "complete", "absolute"),
    _e("absolute", "without limit or exception", "total", "utter", "adamant"),
    _e("utter", "complete, usually of something bad", "absolute", "total", "sheer"),
    _e("sheer", "nothing but that, and nothing else mixed in", "utter", "absolute", "pure"),
    _e("pure", "unmixed with anything else", "sheer", "clean", "authentic"),
    _e("clean", "free of dirt or of complication", "pure", "neat", "plain"),
    _e("finished", "brought to an end", "complete", "done", "polished"),
    _e("done", "no longer in progress", "finished", "complete", "over"),
    _e("over", "at an end", "done", "finished", "past"),
    _e("past", "belonging to a time before now", "over", "former", "previous"),
    _e("former", "the earlier of two", "past", "previous", "prior"),
    _e("previous", "coming before this one", "former", "prior", "past"),
    _e("prior", "earlier, and often taking precedence", "previous", "former", "advance"),
    _e("advance", "going ahead of the rest, or beforehand", "prior", "early", "forward"),
    _e("early", "before the expected time", "advance", "prompt", "soon"),
    _e("prompt", "happening without delay", "early", "immediate", "swift"),
    _e("immediate", "with nothing in between, in time or space", "prompt", "instant", "direct"),
    _e("instant", "taking no time at all", "immediate", "swift", "sudden"),
    _e("sudden", "happening without warning", "instant", "abrupt", "swift"),
    _e("swift", "moving quickly", "instant", "rapid", "prompt"),
    _e("rapid", "at high speed", "swift", "quick", "brisk"),
    _e("quick", "taking little time", "rapid", "brisk", "swift"),
    _e("brisk", "quick and energetic", "quick", "rapid", "lively"),
    _e("lively", "full of energy", "brisk", "spirited", "animated"),
    _e("spirited", "showing energy and determination", "lively", "animated", "bold"),
    _e("animated", "full of movement and expression", "spirited", "lively", "expressive"),
    _e("expressive", "showing feeling clearly", "animated", "eloquent", "vivid"),
    _e("vivid", "bright, clear and strongly felt", "expressive", "striking", "intense"),
    _e("striking", "impossible not to notice", "vivid", "remarkable", "bold"),
    _e("remarkable", "worth remarking on", "striking", "notable", "exceptional"),
    _e("notable", "worth noticing or recording", "remarkable", "significant", "prominent"),
    _e("significant", "large enough or important enough to matter", "notable", "considerable", "salient"),
    _e("salient", "standing out as important", "significant", "prominent", "notable"),
    _e("prominent", "sticking out, or well known", "salient", "notable", "conspicuous"),
    _e("conspicuous", "easily seen, and hard to miss", "prominent", "obvious", "striking"),
    _e("obvious", "needing no explanation", "conspicuous", "clear", "evident"),
    _e("evident", "plain from what can be seen", "obvious", "apparent", "clear"),
    _e("apparent", "seeming so, and possibly actually so", "evident", "obvious", "seeming"),
    _e("seeming", "appearing a certain way, without promising it", "apparent", "ostensible", "evident"),
    _e("ostensible", "the reason given, rather than the real one", "seeming", "apparent", "nominal"),
    _e("nominal", "in name only", "ostensible", "token", "slight"),
    _e("token", "done as a gesture rather than in earnest", "nominal", "slight", "modest"),
    _e("slight", "small in amount or degree", "token", "scant", "modest"),
    _e("considerable", "large enough to take seriously", "significant", "substantial", "ample"),
    _e("substantial", "solid, and of real size or worth", "considerable", "significant", "sturdy"),
    _e("exceptional", "far outside the usual", "remarkable", "extraordinary", "rare"),
    _e("extraordinary", "well beyond the ordinary", "exceptional", "remarkable", "rare"),
    _e("rare", "not often found", "exceptional", "scarce", "extraordinary"),
    _e("fleeting", "over almost as soon as it began", "brief", "elusive", "transient"),
    _e("transient", "lasting only a short while", "fleeting", "brief", "temporary"),
    _e("temporary", "meant to last only for now", "transient", "brief", "provisional"),
    _e("provisional", "in place until something better is arranged", "temporary", "tentative", "interim"),
    _e("tentative", "not settled, and open to change", "provisional", "cautious", "hesitant"),
    _e("hesitant", "holding back out of doubt", "tentative", "cautious", "reluctant"),
    _e("reluctant", "unwilling, but perhaps doing it anyway", "hesitant", "unwilling", "wary"),
    _e("unwilling", "not wanting to", "reluctant", "hesitant", "averse"),
    _e("averse", "having a settled dislike of something", "unwilling", "reluctant", "opposed"),
    _e("opposed", "against it", "averse", "contrary", "hostile"),
    _e("contrary", "going the other way, sometimes for the sake of it", "opposed", "stubborn", "perverse"),
    _e("perverse", "deliberately going against what is sensible", "contrary", "obstinate", "stubborn"),
    _e("hostile", "actively unfriendly", "opposed", "antagonistic", "aggressive"),
    _e("antagonistic", "setting yourself against someone", "hostile", "aggressive", "opposed"),
    _e("aggressive", "pushing forward forcefully", "hostile", "antagonistic", "forceful"),
    _e("forceful", "strong and hard to resist", "aggressive", "assertive", "emphatic"),
    _e("assertive", "stating what you want clearly and firmly", "forceful", "confident", "emphatic"),
    _e("emphatic", "said with force, leaving no doubt", "assertive", "forceful", "adamant"),
    _e("confident", "sure of yourself", "assertive", "assured", "bold"),
    _e("assured", "certain, and showing it calmly", "confident", "composed", "certain"),
    _e("certain", "with no doubt at all", "assured", "sure", "definite"),
    _e("sure", "having no doubt", "certain", "confident", "definite"),
    _e("definite", "clearly settled and not vague", "certain", "sure", "explicit"),
    _e("explicit", "stated outright, leaving no doubt", "definite", "clear", "unambiguous"),
    _e("unambiguous", "able to be read only one way", "explicit", "clear", "precise"),
    _e("implicit", "meant but never actually said", "tacit", "understood", "vague"),
    _e("tacit", "agreed without ever being spoken", "implicit", "understood", "silent"),
    _e("understood", "known without needing to be stated", "tacit", "implicit", "obvious"),
    _e("silent", "making no sound, or saying nothing", "tacit", "quiet", "mute"),
    _e("mute", "not speaking, by choice or otherwise", "silent", "quiet", "reserved"),
    _e("hazy", "unclear, like something seen through mist", "vague", "obscure", "faint"),
    _e("faint", "barely there", "hazy", "slight", "subtle"),
    _e("fine", "very thin, or very good", "delicate", "subtle", "refined"),
    _e("frail", "weak and easily harmed", "fragile", "delicate", "feeble"),
    _e("feeble", "lacking strength or conviction", "frail", "weak", "faint"),
    _e("weak", "lacking strength", "feeble", "frail", "slight"),
    _e("hardy", "able to survive hard conditions", "resilient", "sturdy", "robust"),
    _e("industrious", "working hard and steadily", "diligent", "assiduous", "productive"),
    _e("productive", "getting a lot done", "industrious", "efficient", "effective"),
    _e("efficient", "getting it done without waste", "productive", "effective", "streamlined"),
    _e("effective", "actually achieving what was wanted", "efficient", "productive", "successful"),
    _e("successful", "having achieved the aim", "effective", "accomplished", "fruitful"),
    _e("fruitful", "producing good results", "successful", "productive", "rewarding"),
    _e("rewarding", "worth the effort it took", "fruitful", "satisfying", "valuable"),
    _e("satisfying", "leaving you content", "rewarding", "fulfilling", "pleasing"),
    _e("fulfilling", "meeting a deeper need, not just a want", "satisfying", "rewarding", "meaningful"),
    _e("meaningful", "having real significance", "fulfilling", "significant", "profound"),
    _e("pleasing", "giving pleasure", "satisfying", "agreeable", "delightful"),
    _e("agreeable", "pleasant, and easy to get along with", "pleasing", "amiable", "congenial"),
    _e("amiable", "friendly and good-natured", "agreeable", "congenial", "affable"),
    _e("affable", "easy to talk to", "amiable", "congenial", "approachable"),
    _e("congenial", "suiting your temperament", "amiable", "affable", "agreeable"),
    _e("approachable", "easy to go up to and speak with", "affable", "amiable", "friendly"),
    _e("friendly", "behaving as a friend would", "approachable", "kind", "warm"),
    _e("warm", "kind and welcoming, or not cold", "friendly", "kind", "gentle"),
    _e("delightful", "giving a lot of pleasure", "pleasing", "charming", "lovely"),
    _e("charming", "pleasant in a way that wins people over", "delightful", "engaging", "lovely"),
    _e("engaging", "holding your interest and goodwill", "charming", "interesting", "appealing"),
    _e("appealing", "attractive, or asking for sympathy", "engaging", "charming", "attractive"),
    _e("attractive", "drawing you toward it", "appealing", "lovely", "engaging"),
    _e("lovely", "beautiful or very pleasant", "delightful", "attractive", "charming"),
    _e("interesting", "worth paying attention to", "engaging", "curious", "notable"),
    _e("valuable", "worth a lot, in money or otherwise", "useful", "rewarding", "precious"),
    _e("precious", "valuable enough to be careful with", "valuable", "rare", "cherished"),
    _e("cherished", "held dear over a long time", "precious", "valued", "beloved"),
    _e("valued", "regarded as worth having", "cherished", "valuable", "respected"),
    _e("beloved", "deeply loved", "cherished", "dear", "treasured"),
    _e("dear", "loved, or expensive", "beloved", "precious", "cherished"),
    _e("treasured", "kept and valued carefully", "beloved", "cherished", "precious"),
    _e("respected", "regarded highly by others", "valued", "esteemed", "admired"),
    _e("esteemed", "held in high regard", "respected", "admired", "revered"),
    _e("admired", "looked up to", "esteemed", "respected", "revered"),
    _e("revered", "regarded with deep respect", "admired", "esteemed", "venerated"),
    _e("venerated", "treated with reverence, often for age or wisdom", "revered", "esteemed", "admired"),
    _e("grave", "serious, and possibly worrying", "earnest", "solemn", "serious"),
    _e("solemn", "serious and formal", "grave", "serious", "earnest"),
    _e("serious", "not joking, and mattering", "solemn", "grave", "deep"),
    _e("strict", "insisting the rules are followed", "rigorous", "stern", "firm"),
    _e("stern", "serious and disapproving", "strict", "grave", "firm"),
    _e("firm", "not giving way", "stern", "strict", "resolute"),
    _e("lax", "not strict enough", "negligent", "slack", "careless"),
    _e("slack", "loose, or not putting the effort in", "lax", "careless", "sloppy"),
    _e("remiss", "having failed in a duty", "negligent", "careless", "lax"),
    _e("slapdash", "done hurriedly and badly", "sloppy", "careless", "hasty"),
    _e("spontaneous", "done on the spur of the moment", "impulsive", "natural", "unplanned"),
    _e("natural", "not forced or artificial", "spontaneous", "genuine", "easy"),
    _e("easy", "not requiring much effort", "natural", "smooth", "simple"),
    _e("simple", "not complicated", "easy", "plain", "clean"),
    _e("unplanned", "not decided in advance", "spontaneous", "impulsive", "sudden"),
    _e("decisive", "able to decide quickly and firmly", "resolute", "firm", "confident"),
    _e("stark", "bare, plain, and often harsh", "plain", "severe", "bleak"),
    _e("severe", "harsh, or very serious", "stark", "stern", "strict"),
    _e("bleak", "cold and offering little hope", "stark", "severe", "grim"),
    _e("grim", "unpleasant and unrelenting", "bleak", "severe", "stark"),
    _e("streamlined", "shaped or arranged to remove drag", "efficient", "smooth", "simple"),
    _e("apt", "exactly suited to the occasion", "pithy", "fitting", "appropriate"),
    _e("fitting", "suitable for the situation", "apt", "appropriate", "proper"),
    _e("appropriate", "right for the circumstances", "fitting", "apt", "proper"),
    _e("proper", "correct according to the rules or the occasion", "appropriate", "fitting", "correct"),
    _e("taut", "pulled tight", "stiff", "tense", "tight"),
    _e("tense", "stretched, or anxious", "taut", "tight", "anxious"),
    _e("tight", "held firmly, with no slack", "taut", "tense", "firm"),
    _e("anxious", "worried about what might happen", "tense", "wary", "uneasy"),
    _e("uneasy", "not quite comfortable about something", "anxious", "wary", "tense"),
    _e("interim", "for the time being", "provisional", "temporary", "transient"),
    _e("mild", "not severe, and not strong", "gentle", "moderate", "temperate"),

    # ── Closing the loops ───────────────────────────────────
    # Every `near` above has to be an entry too, or a walk hits a dead end.
    _e("direct", "going straight there, or saying it straight", "immediate", "frank", "forward"),
    _e("forward", "toward the front, or a little too bold", "direct", "advance", "assertive"),
    _e("generous", "giving more than required", "lavish", "kind", "ample"),
    _e("intense", "very strong in degree or feeling", "vivid", "severe", "deep"),
    _e("lasting", "continuing for a long time", "enduring", "durable", "permanent"),
    _e("permanent", "meant to stay indefinitely", "lasting", "enduring", "constant"),
    _e("puzzling", "hard to make sense of", "enigmatic", "obscure", "confusing"),
    _e("confusing", "making things harder to understand than they were", "puzzling", "obscure", "ambiguous"),
    _e("remote", "far off, in distance or in manner", "aloof", "distant", "rare"),
    _e("distant", "far away, or emotionally withdrawn", "remote", "aloof", "detached"),
    _e("soon", "before long", "early", "prompt", "imminent"),
    _e("imminent", "about to happen", "soon", "immediate", "impending"),
    _e("impending", "coming, and usually unwelcome", "imminent", "soon", "looming"),
    _e("looming", "approaching and hard to ignore", "impending", "imminent", "prominent"),
    _e("sophisticated", "refined, and aware of the finer distinctions", "nuanced", "refined", "worldly"),
    _e("worldly", "experienced in how the world actually works", "sophisticated", "shrewd", "practical"),
    _e("spare", "extra, or plain and unadorned", "superfluous", "sparse", "plain"),
    _e("supportive", "helping somebody keep going", "helpful", "kind", "encouraging"),
    _e("encouraging", "giving somebody reason to carry on", "supportive", "helpful", "hopeful"),
    _e("hopeful", "expecting something good", "encouraging", "optimistic", "positive"),
    _e("optimistic", "expecting things to turn out well", "hopeful", "positive", "confident"),
    _e("positive", "favourable, or certain of something", "optimistic", "hopeful", "confident"),
    _e("wise", "knowing what matters, from having lived", "judicious", "sage", "prudent"),
    _e("sage", "wise in a calm, considered way", "wise", "judicious", "venerated"),
)

BY_WORD: dict[str, Entry] = {entry.word: entry for entry in ENTRIES}


def walk(rng, length: int, start: str | None = None) -> list[Entry]:
    """A path through the thesaurus, one word to a neighbouring one.

    Never revisits a word inside a single walk — the point is the journey, and
    coming back to where you were is not one. If it paints itself into a
    corner it jumps somewhere new rather than stopping short.
    """
    entries = list(ENTRIES)
    current = BY_WORD.get(start or "") or rng.choice(entries)
    seen = {current.word}
    path = [current]

    while len(path) < length:
        options = [
            BY_WORD[name]
            for name in current.near
            if name in BY_WORD and name not in seen
        ]
        if not options:
            options = [e for e in entries if e.word not in seen]
            if not options:
                break
        current = rng.choice(options)
        seen.add(current.word)
        path.append(current)
    return path
