"""Set up the local PostgreSQL: initialise the cluster and load the data.

    python tools/get_postgres.py

Safe to run again — it skips whatever is already done.

It does not download anything. The binaries are expected in .tools/pgsql
already; fetching 300MB is a thing somebody should decide to do rather
than have happen as a side effect of a script. The message below says
where they come from if they are missing.

Nothing here touches the machine outside this project: no installer, no
service, no admin rights, no registry. The cluster lives in .tools,
listens on 127.0.0.1 and a port nobody else would pick, and undoing all
of it is deleting .tools/pgdata.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from code_coach import pg_server  # noqa: E402

WHERE_FROM = """
PostgreSQL's binaries are not in .tools/pgsql.

The Windows builds come as a plain zip from EnterpriseDB, who publish
them for postgresql.org — no installer and no admin rights needed:

    https://www.enterprisedb.com/download-postgresql-binaries

Download the 64-bit zip, extract it, and put the `pgsql` folder it
contains at .tools/pgsql. Then run this again.
"""

#: The same people and orders as the SQLite database, so a query can be
#: read in both dialects and the difference on screen is the SQL.
#:
#: Plus the columns SQLite has no answer for — a real timestamp, an
#: array, JSONB, an identity column, a generated column — because those
#: are most of what makes PostgreSQL worth practising separately.
SCHEMA = """
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id       integer PRIMARY KEY,
    name     text NOT NULL,
    city     text,
    age      integer,
    email    text,
    active   boolean DEFAULT true,
    joined   timestamptz,
    tags     text[],
    profile  jsonb
);

CREATE TABLE orders (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  integer REFERENCES users(id),
    item     text NOT NULL,
    price    numeric(10, 2) NOT NULL,
    placed   timestamptz
);

INSERT INTO users (id, name, city, age, email, active, joined, tags, profile)
VALUES
    (1, 'Alex',   'Denver', 30, 'alex@example.com',  true,
     '2024-01-15 09:30+00', ARRAY['admin', 'beta'],
     '{"plan": "pro",  "seats": 3}'),
    (2, 'Bailey', 'Austin', 24, NULL,                true,
     '2024-03-02 14:05+00', ARRAY['beta'],
     '{"plan": "free"}'),
    (3, 'Casey',  'Denver', 41, 'casey@example.com', false,
     '2023-11-20 08:00+00', ARRAY[]::text[],
     '{"plan": "pro",  "seats": 12}'),
    (4, 'Devon',  'Boston', 17, 'devon@example.com', true,
     '2024-05-30 17:45+00', ARRAY['student'],
     '{"plan": "free", "referred_by": 1}'),
    (5, 'Erin',   'Austin', 35, NULL,                true,
     '2024-02-11 11:15+00', ARRAY['admin'],
     '{"plan": "team", "seats": 5}');

INSERT INTO orders (id, user_id, item, price, placed) VALUES
    (1, 1, 'Keyboard',  49.99, '2024-04-01 10:00+00'),
    (2, 1, 'Monitor',  219.00, '2024-04-03 16:20+00'),
    (3, 2, 'Mouse',     19.50, '2024-04-05 09:10+00'),
    (4, 3, 'Desk',     315.75, '2024-04-06 12:00+00'),
    (5, 5, 'Lamp',      34.25, '2024-04-09 19:30+00'),
    (6, 5, 'Keyboard',  49.99, '2024-04-11 08:45+00');

-- The identity column has to be told where the hand-written ids
-- stopped, or the first INSERT that leaves id out collides with row 1.
SELECT setval(
    pg_get_serial_sequence('orders', 'id'),
    (SELECT max(id) FROM orders)
);
"""


def run(argv: list[str], **kw) -> subprocess.CompletedProcess:
    return subprocess.run(
        argv, capture_output=True, text=True, errors="replace", **kw)


def main() -> int:
    if not pg_server.available():
        print(WHERE_FROM.strip())
        return 1

    base = pg_server.home()
    print(f"PostgreSQL binaries: {base}")

    if not pg_server.initialised():
        print(f"Creating the cluster in {pg_server.data_dir()} …")
        initdb = pg_server._binary("initdb")
        password_file = pg_server.TOOLS / "pgpass.tmp"
        password_file.write_text(pg_server.PASSWORD, encoding="ascii")
        try:
            done = run([
                str(initdb),
                "-D", str(pg_server.data_dir()),
                "-U", pg_server.USER,
                "--auth-local=trust",
                "--auth-host=scram-sha-256",
                f"--pwfile={password_file}",
                "--encoding=UTF8",
                "--locale=C",
            ])
        finally:
            password_file.unlink(missing_ok=True)
        if done.returncode != 0:
            print(done.stderr[-800:])
            return 1
        print("  cluster created")
    else:
        print("Cluster already exists — leaving it alone.")

    ok, why = pg_server.start()
    if not ok:
        print(why)
        return 1
    print(f"Server up on {pg_server.HOST}:{pg_server.PORT}")

    psql = pg_server._binary("psql")
    made = run(
        [str(psql), "-h", pg_server.HOST, "-p", str(pg_server.PORT),
         "-U", pg_server.USER, "-d", "postgres", "-tAc",
         f"SELECT 1 FROM pg_database WHERE datname = '{pg_server.DATABASE}'"],
        env=pg_server.env())
    if made.stdout.strip() != "1":
        created = run(
            [str(psql), "-h", pg_server.HOST, "-p", str(pg_server.PORT),
             "-U", pg_server.USER, "-d", "postgres", "-c",
             f"CREATE DATABASE {pg_server.DATABASE}"],
            env=pg_server.env())
        if created.returncode != 0:
            print(created.stderr[-800:])
            return 1
        print(f"  database {pg_server.DATABASE} created")

    loaded = run(
        [str(psql), "-h", pg_server.HOST, "-p", str(pg_server.PORT),
         "-U", pg_server.USER, "-d", pg_server.DATABASE,
         "-v", "ON_ERROR_STOP=1", "-q", "-f", "-"],
        input=SCHEMA, env=pg_server.env())
    if loaded.returncode != 0:
        print(loaded.stderr[-800:])
        return 1
    print("  sample data loaded")

    from code_coach.pg_runner import run_postgres

    out, err, code = run_postgres(
        "SELECT name, city FROM users WHERE city = 'Denver' ORDER BY name;")
    print("\nA query, to prove it works:")
    print(out or err)
    return 0 if code == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
