"""The Dart cheat sheet."""

from __future__ import annotations

from code_coach.reference import Entry, Section, Sheet, register


def _e(code: str, note: str = "") -> Entry:
    return Entry(code=code, note=note)


SHEET = Sheet(
    language="dart",
    sections=(
        Section(
            "The first minute",
            "What you write before you have written anything.",
            (
                _e("print(value);", "print anything"),
                _e("final name = 'Alex';", "set once, type inferred — start here"),
                _e("var count = 0;", "for values that change"),
                _e("const pi = 3.14;", "known at compile time"),
                _e("int add(int a, int b) {\n  return a + b;\n}", "return type first"),
                _e("int add(int a, int b) => a + b;", "one expression, no braces"),
                _e("'Hi, $name!'", "a bare name needs no braces"),
                _e("'Sum: ${a + b}'", "braces for an expression"),
                _e("if (a == b) {", "== compares values, not identity"),
                _e("for (final n in nums) {", "walk values"),
                _e("void main() {", "every program starts here"),
                _e("// a note to your later self", "and /// for a doc comment"),
            ),
        ),
        Section(
            "Null safety",
            "The compiler tracks what can be null. Most Dart friction is here.",
            (
                _e("String name;", "cannot be null, must be initialised"),
                _e("String? name;", "may be null — a different type"),
                _e("name?.length", "null if name is, instead of throwing"),
                _e("name ?? 'unknown'", "a fallback when null"),
                _e("name ??= 'unknown';", "assign only if currently null"),
                _e("name!", "'this is not null' — throws if you are wrong"),
                _e("late String name;", "set before first read, promise"),
                _e("if (name != null) {", "narrows to non-null inside"),
                _e("final n = name?.length ?? 0;", "the everyday combination"),
                _e("required this.name,", "a named parameter with no default"),
            ),
        ),
        Section(
            "Lists",
            "Ordered and growable, unless you ask for otherwise.",
            (
                _e("final nums = <int>[1, 2, 3];", "typed literal"),
                _e("final empty = <int>[];", "an empty one needs its type"),
                _e("nums.length", "a property"),
                _e("nums[0]", "and nums.first, nums.last"),
                _e("nums.add(4);", "and addAll(more)"),
                _e("nums.removeLast();", "and removeAt(i), remove(value)"),
                _e("nums.contains(2)", "present?"),
                _e("nums.indexOf(2)", "-1 if absent"),
                _e("nums.sublist(1, 3)", "a copy of part"),
                _e("[...nums]", "a shallow copy"),
                _e("nums.join('-')", "to a string"),
                _e("List<int>.filled(3, 0)", "fixed length — add() throws"),
                _e("List.generate(5, (i) => i)", "0..4"),
                _e("nums.sort((a, b) => a - b);", "in place, returns nothing"),
                _e("nums.reversed.toList()", "reversed is lazy"),
            ),
        ),
        Section(
            "Walking a collection",
            "These are lazy. toList() is what actually runs them.",
            (
                _e("nums.map((n) => n * 2).toList()", "without toList it is an Iterable"),
                _e("nums.where((n) => n > 2).toList()", "Dart's filter"),
                _e(
                    "nums.fold<int>(0, (sum, n) => sum + n)",
                    "the type argument is needed; it won't infer",
                ),
                _e("nums.reduce((a, b) => a + b)", "no seed — throws when empty"),
                _e("nums.forEach(print);", "no value out"),
                _e("nums.firstWhere((n) => n > 2)", "throws if none; orElse: avoids it"),
                _e("nums.any((n) => n > 2)", "and every()"),
                _e("nums.expand((row) => row).toList()", "flatten"),
                _e("nums.take(3)", "and skip(3)"),
                _e("nums.toSet()", "drop duplicates"),
            ),
        ),
        Section(
            "Strings",
            "Immutable — every one of these returns a new string.",
            (
                _e("text.length", "characters"),
                _e("text.toUpperCase()", "and toLowerCase()"),
                _e("text.trim()", "whitespace off both ends"),
                _e("text.contains('ab')", "substring present?"),
                _e("text.startsWith('a')", "and endsWith"),
                _e("text.indexOf('a')", "-1 if absent"),
                _e("text.substring(0, 3)", "a piece of it"),
                _e("text.split(',')", "to a list"),
                _e("text.replaceAll('a', 'b')", "and replaceFirst"),
                _e("text * 3", "repeat — an operator, not a method"),
                _e("text.padLeft(2, '0')", "'7' becomes '07'"),
                _e("text.split('')", "to a list of characters"),
                _e("int.parse('42')", "and int.tryParse, which returns null"),
                _e("value.toString()", "and toStringAsFixed(2)"),
            ),
        ),
        Section(
            "Maps and sets",
            "Lookup by key, and membership without duplicates.",
            (
                _e("final user = <String, int>{};", "typed literal"),
                _e("user['age'] = 30;", "set"),
                _e("user['age']", "null if missing — never throws"),
                _e("user['age'] ?? 0", "the everyday read"),
                _e("counts[k] = (counts[k] ?? 0) + 1;", "the counting idiom"),
                _e("user.containsKey('age')", "and containsValue"),
                _e("user.putIfAbsent(k, () => [])", "grouping into lists"),
                _e("user.remove('age');", "returns the value"),
                _e("for (final e in user.entries) {", "e.key and e.value"),
                _e("user.keys", "and user.values — both lazy"),
                _e("{...user, 'age': 31}", "a copy with one field changed"),
                _e("final seen = <int>{};", "a set; {} alone is a Map"),
                _e("seen.add(x);", "and contains, remove"),
            ),
        ),
        Section(
            "Deciding",
            "Conditions must be real booleans — there is no truthiness.",
            (
                _e("a == b", "value equality; identical(a, b) for identity"),
                _e("a != b", "the matching not-equal"),
                _e("a && b", "both; stops early"),
                _e("a || b", "either; stops early"),
                _e("!a", "flip it"),
                _e("cond ? x : y", "the ternary"),
                _e("if (items.isEmpty) return;", "not `if (!items)` — that will not compile"),
                _e("n.isEven", "a property on int, and isOdd"),
                _e("value is String", "type test, and narrows below it"),
                _e("value is! String", "the negative form"),
                _e("switch (day) {\n  case 'Sat':\n    return 'weekend';\n}", "cases need a return or break"),
            ),
        ),
        Section(
            "Loops",
            "The shapes, and where Dart names things differently.",
            (
                _e("for (final n in nums) {", "values — the usual one"),
                _e("for (var i = 0; i < n; i++) {", "when you need the index"),
                _e("for (var i = n - 1; i >= 0; i--) {", "backwards"),
                _e("while (cond) {", "when the end is a condition"),
                _e("do {\n} while (cond);", "runs at least once"),
                _e("break;", "leave the loop"),
                _e("continue;", "skip to the next turn"),
                _e("for (final e in map.entries) {", "key and value"),
                _e("[for (final n in nums) n * 2]", "collection-for, inside the literal"),
                _e("[if (ready) 'yes']", "collection-if — no ternary needed"),
            ),
        ),
        Section(
            "Classes",
            "Constructors do most of the work, and there are several.",
            (
                _e("class Point {", "and `final` fields inside it"),
                _e("Point(this.x, this.y);", "assigns the fields for you"),
                _e("Point({required this.x});", "named, and required"),
                _e("Point.origin() : x = 0, y = 0;", "a named constructor"),
                _e("const Point(this.x, this.y);", "buildable at compile time"),
                _e("factory Point.of(v) {", "may return a cached instance"),
                _e("_private", "a leading underscore is library-private"),
                _e("class Dog extends Animal {", "one superclass"),
                _e("class Dog implements Pet {", "any number of interfaces"),
                _e("class Dog extends Animal with Barking {", "a mixin"),
                _e("@override", "not required, but the analyzer wants it"),
                _e("String toString() => 'Point($x, $y)';", "what print uses"),
            ),
        ),
        Section(
            "Async",
            "Futures for one value, Streams for many.",
            (
                _e("Future<int> load() async {", "async always returns a Future"),
                _e("final data = await fetch();", "only inside async"),
                _e("await Future.wait([a, b]);", "together, not one after another"),
                _e("Future.delayed(Duration(seconds: 1))", "later, without blocking"),
                _e("try {\n  await job();\n} catch (e) {\n  print(e);\n}", "catching an await"),
                _e("Stream<int> counter() async* {", "a stream generator"),
                _e("yield value;", "hand one out and carry on"),
                _e("await for (final v in stream) {", "consume a stream"),
                _e("stream.listen((v) => print(v));", "the callback form"),
                _e("unawaited(job());", "deliberately not waiting, and saying so"),
            ),
        ),
        Section(
            "Errors",
            "Throwing, catching, and the block that tidies up.",
            (
                _e("throw ArgumentError('message');", "the specific type"),
                _e("throw Exception('message');", "when nothing fits better"),
                _e("try {\n  risky();\n} on FormatException {\n}", "catch one type"),
                _e("} catch (e, stack) {", "the error and where it came from"),
                _e("} finally {", "runs either way"),
                _e("rethrow;", "pass it on, keeping the stack"),
                _e("assert(n > 0);", "debug builds only"),
            ),
        ),
        Section(
            "Records and patterns",
            "Dart 3: several values without inventing a class.",
            (
                _e("(int, String) pair() => (1, 'a');", "a record type"),
                _e("({int x, int y}) p = (x: 1, y: 2);", "named fields"),
                _e("final (a, b) = pair();", "destructure"),
                _e("final (:x, :y) = point;", "by name"),
                _e("switch (shape) {\n  case Circle(:final r):\n}", "pattern match"),
                _e("sealed class Shape {}", "makes a switch exhaustive"),
                _e("final result = switch (n) { 1 => 'one', _ => 'many' };", "switch as an expression"),
            ),
        ),
        Section(
            "Imports",
            "Getting at the library, and at your own files.",
            (
                _e("import 'dart:math';", "built in — no package needed"),
                _e("import 'dart:collection';", "Queue, LinkedHashMap"),
                _e("import 'dart:convert';", "jsonEncode, jsonDecode"),
                _e("import 'package:http/http.dart';", "from pub"),
                _e("import 'models/user.dart';", "your own file, relative"),
                _e("import 'dart:math' as math;", "namespaced"),
                _e("import 'x.dart' show Foo;", "and hide Bar"),
                _e("export 'src/thing.dart';", "re-export from a barrel file"),
            ),
        ),
    ),
)

register(SHEET)
